### ISSUE TITLE
Stopped working after an update on SteamGifts

### ISSUE THREAD

**Issue by bjarnejorgensen** [Sighery/RaChart#5]
It seems SteamGifts has introduced a "View Bookmarked" option in the "Discussions" drop down.
This make the load of RaChart fail.

See 

https://www.steamgifts.com/discussion/riOvr/userscript-rachart-enhancer-0400-major-update-cache-for-subs-and-bundle-detection/search?page=7#FwDGwvu

for a potential fix. It works as a *work around* for now.

**Comment by lainverse** [comment]
I changed row
var discDropdown = document.querySelector("a[class~='nav__button'][href='/discussions']");
to
var discDropdown = document.querySelector("a[class~='nav__button'][href^='/discussions']");

BTW, why "~="?
Guess there were no separate "nav__button" class. I'd change it to this:
var discDropdown = document.querySelector(".nav__button[href^='/discussions']");

**Comment by Sighery** [comment]
Thanks for the possible fixes. I'll try and review them and the recent SG changes and hopefully I'll be able to push out an update within the week, if my schedule allows it.

**Comment by Sighery** [comment]
Sorry for the delay, folks. Got kinda busy with vacations, then new job, and then work trips. Should be fixed with https://github.com/Sighery/RaChart/commit/6f3aa8520af163e57065acc670d7d8358caac709. Pushed a new update as well so it should roll out within a day/week, depending on your script manager. On Tampermonkey you can trigger a new check within the menu to hopefully get the update immediately.
